### PR TITLE
Nurik

### PR DESCRIPTION
**Pull request by Nurikaga**

### CODE REVIEW

**Comment by OksanaSkrynnik** [comment]
all good

**Comment by OksanaSkrynnik** [comment]
done

**Review by OksanaSkrynnik — APPROVED** [review]
good

**Comment by OksanaSkrynnik** [comment]
good

**Review by OksanaSkrynnik — APPROVED** [review]
approved

**Comment by OksanaSkrynnik** [comment]
good

**Review by OksanaSkrynnik — APPROVED** [review]
all done

**Comment by OksanaSkrynnik** [comment]
done

**Review by kZhaanbaev — APPROVED** [review]

**Review by OksanaSkrynnik — APPROVED** [review]
perfect

**Review by OksanaSkrynnik — APPROVED** [review]

**Pull request merged**
